INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Clasica',  0,   'APARIENCIA', 'apariencia_clasica.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Espacial', 100, 'APARIENCIA', 'espacial_shop_image.jpg');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Hardware', 100, 'APARIENCIA', 'hardware_shop_image.jpg');

INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Original',         0, 'AVATAR', 'user_profile_image_original.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Dave',             1, 'AVATAR', 'user_profile_image_0.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Sr bigotes',       2, 'AVATAR', 'user_profile_image_1.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Científica',       3, 'AVATAR', 'user_profile_image_2.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Bruno',            4, 'AVATAR', 'user_profile_image_3.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Mr. Secreto',      5, 'AVATAR', 'user_profile_image_4.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Dae Dev',          6, 'AVATAR', 'user_profile_image_5.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Developer',        7, 'AVATAR', 'user_profile_image_6.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Ingeniera',        8, 'AVATAR', 'user_profile_image_7.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Azafata',          9, 'AVATAR', 'user_profile_image_8.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Alfred',          10, 'AVATAR', 'user_profile_image_9.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Profesora',       11, 'AVATAR', 'user_profile_image_10.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Señora formal',   12, 'AVATAR', 'user_profile_image_11.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Astronauta',      13, 'AVATAR', 'user_profile_image_12.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Anciano feliz',   14, 'AVATAR', 'user_profile_image_13.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Chico tranquilo', 15, 'AVATAR', 'user_profile_image_14.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Barbero',         16, 'AVATAR', 'user_profile_image_15.png');
INSERT INTO producto (nombre, precio, tipo, producto_id) VALUES('Sr desonfiado',   17, 'AVATAR', 'user_profile_image_16.png');